data:extend({
  {
    type = "recipe",
    name = "bm-warp-drive-part",
    icons = {
      {
        icon = "__biological-machines-warp-drive__/graphics/quantum-stabilizer/quantum-stabilizer-icon.png",
      },
      {
        icon = "__biological-machines-warp-drive__/graphics/under-construction.png",
      },
    },
    categories = {"electromagnetics"},
    enabled = false,
    allow_productivity = false,
    allow_decomposition = false,
    energy_required = 120,
    ingredients = {
      {type = "item", name = "quantum-processor", amount = 10},
      {type = "item", name = "low-density-structure", amount = 10},
      {type = "item", name = "beacon", amount = 1},
      {type = "item", name = "supercapacitor", amount = 10},
      {type = "item", name = "tungsten-plate", amount = 10},
    },
    results = {{type = "item", name = "bm-warp-drive-part", amount = 1}},
  },
  {
    type = "recipe",
    name = "bm-warp-drive",
    icon = "__biological-machines-warp-drive__/graphics/quantum-stabilizer/quantum-stabilizer-icon.png",
    categories = {"advanced-crafting", "electromagnetics"},
    enabled = false,
    allow_productivity = false,
    allow_decomposition = false,
    energy_required = 60,
    ingredients = {{type = "item", name = "bm-warp-drive-part", amount = 20}},
    results = {{type = "item", name = "bm-warp-drive", amount = 1}},
    surface_conditions = {{property = "gravity", min = 0, max = 0}},
  },
  {
    type = "recipe",
    name = "bm-warp-power-cell",
    --icon = "__biological-machines-k2-assets__/graphics/warp-power-cell-light.png",
    categories = {"electromagnetics"},
    subgroup = "aquilo-processes",
    order = "z-a",
    enabled = false,
    allow_productivity = true,
    allow_decomposition = false,
    energy_required = 120,
    ingredients = {
      {type = "item", name = "uranium-235", amount = 1},
      {type = "item", name = "quantum-processor", amount = 5},
      {type = "item", name = "tungsten-carbide", amount = 10},
      {type = "item", name = "superconductor", amount = 5},
      {type = "item", name = "lithium-plate", amount = 5},
    },
    results = {{type = "item", name = "bm-warp-power-cell", amount = 1}},
  },
  {
    type = "recipe",
    name = "bm-warp",
    icon = "__biological-machines-k2-assets__/graphics/matter.png",
    categories = {"bm-warp-drive"},
    subgroup = "space-platform",
    order = "z-a",
    enabled = false,
    --hidden = true,
    --hidden_in_factoriopedia = true,
    allow_productivity = true,
    allow_decomposition = false,
    energy_required = 60,
    ingredients = {{type = "item", name = "bm-warp-power-cell", amount = 1}},
    results = {
      --{type = "item", name = "bm-warp", amount = 1},
      {type = "item", name = "bm-warp-power-cell-used", amount = 1, independent_probability = 0.2}
    },
    --result_is_always_fresh = true,
    hide_from_signal_gui = false,
    raise_on_crafted = true,
  },
  {
    type = "recipe",
    name = "bm-warp-power-cell-recharge",
    --icon = "__biological-machines-k2-assets__/graphics/warp-power-cell.png",
    --[[
    icons = {
      {
        icon = "__biological-machines-k2-assets__/graphics/warp-power-cell-dark.png",
        scale = 0.35,
        shift = {-4, -4},
      },
      {
        icon = "__biological-machines-k2-assets__/graphics/warp-power-cell.png",
        scale = 0.35,
        shift = {4, 4},
        draw_background = true,
      },
    },
    ]]
    icons = {
      {
        icon = "__biological-machines-k2-assets__/graphics/warp-power-cell-dark.png",
      },
      {
        icon = "__biological-machines-warp-drive__/graphics/under-construction.png",
      },
    },
    categories = {"electromagnetics"},
    subgroup = "aquilo-processes",
    order = "z-a",
    enabled = false,
    allow_productivity = false,
    maximum_productivity = 0,
    allow_quality = false,
    allow_decomposition = false,
    energy_required = 60,
    ingredients = {
      {type = "item", name = "uranium-235", amount = 1},
      {type = "item", name = "bm-warp-power-cell-used", amount = 1},
    },
    results = {{type = "item", name = "bm-warp-power-cell", amount = 1}},
    main_product = "bm-warp-power-cell",
  },
})
