data:extend({
  {
    type = "recipe",
    name = "bm-warp-drive",
    icon = "__biological-machines-warp-drive__/graphics/quantum-stabilizer/quantum-stabilizer-icon.png",
    category = "electromagnetics",
    enabled = false,
    allow_productivity = false,
    allow_decomposition = false,
    energy_required = 60,
    ingredients = {
      {type = "item", name = "quantum-processor", amount = 200},
      {type = "item", name = "low-density-structure", amount = 100},
      {type = "item", name = "beacon", amount = 20},
      {type = "item", name = "supercapacitor", amount = 200},
      {type = "item", name = "tungsten-plate", amount = 200},
    },
    results = {{type = "item", name = "bm-warp-drive", amount = 1}},
    surface_conditions = {{property = "gravity", min = 0, max = 0}},
  },
  {
    type = "recipe",
    name = "bm-warp-power-cell",
    icon = "__biological-machines-k2-assets__/graphics/warp-power-cell.png",
    category = "electromagnetics",
    subgroup = "aquilo-processes",
    enabled = false,
    allow_productivity = true,
    allow_decomposition = false,
    energy_required = 1200,
    ingredients = {
      {type = "item", name = "uranium-235", amount = 1},
      {type = "item", name = "quantum-processor", amount = 5},
      {type = "item", name = "tungsten-carbide", amount = 10},
      {type = "item", name = "superconductor", amount = 5},
      {type = "item", name = "lithium-plate", amount = 5},
    },
    results = {{type = "item", name = "bm-warp-power-cell", amount = 1}},
  },
  {
    type = "recipe",
    name = "bm-warp",
    icon = "__biological-machines-k2-assets__/graphics/matter.png",
    category = "bm-warp-drive",
    subgroup = "space-platform",
    order = "z-a",
    enabled = false,
    --hidden = true,
    --hidden_in_factoriopedia = true,
    allow_productivity = false,
    allow_decomposition = false,
    energy_required = 10,
    ingredients = {{type = "item", name = "bm-warp-power-cell", amount = 1}},
    results = {{type = "item", name = "bm-warp", amount = 1}},
    result_is_always_fresh = true,
    hide_from_signal_gui = false,
  },
})
