local item_sounds = require("__base__.prototypes.item_sounds")



data:extend({
  {
    type = "item",
    name = "bm-glass-shard",
    icon = "__biological-machines-planet-wit__/graphics/glass-shard-icon.png",
    subgroup = "bm-wit-processes",
    order = "c-a",
    default_import_location = "bm-wit",
    inventory_move_sound = item_sounds.science_inventory_move,
    pick_sound = item_sounds.science_inventory_pickup,
    drop_sound = item_sounds.science_inventory_move,
    stack_size = 50,
    weight = 2 * kg
  },
  {
    type = "item",
    name = "bm-copper-sulfate",
    icon = "__biological-machines-planet-wit__/graphics/copper-sulfate-icon.png",
    subgroup = "bm-wit-processes",
    order = "a-a",
    default_import_location = "bm-wit",
    inventory_move_sound = item_sounds.resource_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.resource_inventory_move,
    stack_size = 50,
    weight = 2 * kg
  },
  {
    type = "item",
    name = "bm-copper-dust",
    icon = "__biological-machines-k2-assets__/graphics/copper-dust.png",
    subgroup = "bm-wit-processes",
    order = "a-d",
    default_import_location = "bm-wit",
    inventory_move_sound = item_sounds.resource_inventory_move,
    pick_sound = item_sounds.resource_inventory_pickup,
    drop_sound = item_sounds.resource_inventory_move,
    stack_size = 50,
    weight = 2 * kg
  },
  {
    type = "item",
    name = "bm-helium-power-cell",
    icon = "__biological-machines-planet-wit__/graphics/helium-power-cell.png",
    subgroup = "bm-wit-processes",
    order = "c-g",
    default_import_location = "bm-wit",
    inventory_move_sound = item_sounds.wire_inventory_move,
    pick_sound = item_sounds.wire_inventory_pickup,
    drop_sound = item_sounds.wire_inventory_move,
    stack_size = 200,
    weight = 0.5 * kg
  },
  {
    type = "item",
    name = "bm-mixed-gas-power-cell",
    icon = "__biological-machines-planet-wit__/graphics/mixed-gas-power-cell.png",
    subgroup = "bm-wit-processes",
    order = "c-g-a",
    default_import_location = "bm-wit",
    inventory_move_sound = item_sounds.wire_inventory_move,
    pick_sound = item_sounds.wire_inventory_pickup,
    drop_sound = item_sounds.wire_inventory_move,
    stack_size = 100,
    weight = 1 * kg
  },
  {
    type = "item",
    name = "bm-empty-data-disk",
    icon = "__biological-machines-k2-assets__/graphics/empty-data-disk.png",
    subgroup = "bm-wit-processes",
    order = "c-g-b",
    default_import_location = "bm-wit",
    inventory_move_sound = item_sounds.science_inventory_move,
    pick_sound = item_sounds.science_inventory_pickup,
    drop_sound = item_sounds.science_inventory_move,
    stack_size = 100,
    weight = 2 * kg,
  },
  {
    type = "item",
    name = "bm-incomplete-data-disk",
    icon = "__biological-machines-k2-assets__/graphics/incomplete-data-disk.png",
    subgroup = "bm-wit-processes",
    order = "c-g-c",
    default_import_location = "bm-wit",
    inventory_move_sound = item_sounds.science_inventory_move,
    pick_sound = item_sounds.science_inventory_pickup,
    drop_sound = item_sounds.science_inventory_move,
    stack_size = 100,
    weight = 2 * kg,
    spoil_ticks = 2 * minute,
    spoil_result = "bm-empty-data-disk",
  },
  {
    type = "item",
    name = "bm-complete-data-disk",
    icon = "__biological-machines-k2-assets__/graphics/complete-data-disk.png",
    subgroup = "bm-wit-processes",
    order = "c-g-d",
    default_import_location = "bm-wit",
    inventory_move_sound = item_sounds.science_inventory_move,
    pick_sound = item_sounds.science_inventory_pickup,
    drop_sound = item_sounds.science_inventory_move,
    stack_size = 100,
    weight = 2 * kg,
    spoil_ticks = 1 * minute,
    spoil_result = "bm-empty-data-disk",
  },
  {
    type = "tool",
    name = "bm-interstellar-science-pack",
    localised_description = {"item-description.science-pack"},
    icon = "__biological-machines-planet-wit__/graphics/interstellar-science-pack-icon.png",
    subgroup = "science-pack",
    color_hint = { text = "I" },
    order = "m",
    inventory_move_sound = item_sounds.science_inventory_move,
    pick_sound = item_sounds.science_inventory_pickup,
    drop_sound = item_sounds.science_inventory_move,
    stack_size = 200,
    default_import_location = "bm-wit",
    weight = 1 * kg,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    factoriopedia_durability_description_key = "description.factoriopedia-science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value",
    random_tint_color = item_tints.bluish_science,
    spoil_ticks = 1 * minute,
  },
  {
    type = "item",
    name = "bm-advanced-accumulator",
    icon = "__biological-machines-planet-wit__/graphics/advanced-accumulator/advanced-accumulator-icon.png",
    subgroup = "energy",
    order = "e[accumulator]-a[accumulator]-a",
    inventory_move_sound = item_sounds.electric_large_inventory_move,
    pick_sound = item_sounds.electric_large_inventory_pickup,
    drop_sound = item_sounds.electric_large_inventory_move,
    place_result = "bm-advanced-accumulator",
    stack_size = 5,
    weight = 200 * kg,
  },
  --[[
  {
    type = "fluid",
    name = "hydrogen",
    icon = "__biological-machines-planet-wit__/graphics/hydrogen.png",
    subgroup = "fluid",
    default_temperature = 15,
    max_temperature = 1000,
    heat_capacity = "0.2kJ",
    base_color = {0.8, 0.95, 0.95},
    flow_color = {0.95, 1, 1},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "oxygen",
    icon = "__biological-machines-planet-wit__/graphics/oxygen.png",
    subgroup = "fluid",
    default_temperature = 15,
    max_temperature = 1000,
    heat_capacity = "0.2kJ",
    base_color = {0.1, 0.5, 1},
    flow_color = {0.1, 0.75, 1},
    auto_barrel = false
  },
  ]]
  {
    type = "fluid",
    name = "bm-helium",
    icon = "__biological-machines-planet-wit__/graphics/helium.png",
    subgroup = "fluid",
    default_temperature = 15,
    max_temperature = 1000,
    heat_capacity = "0.2kJ",
    base_color = {1, 0.05, 0.05},
    flow_color = {1, 0.45, 0.50},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "bm-glass-dust",
    icon = "__biological-machines-k2-assets__/graphics/glass-dust.png",
    subgroup = "fluid",
    default_temperature = 15,
    max_temperature = 1000,
    heat_capacity = "0.2kJ",
    base_color = {0.5, 0.5, 0.5},
    flow_color = {0.65, 0.65, 0.65},
    auto_barrel = false
  },
})
