local hit_effects = require("__base__.prototypes.entity.hit-effects")
local sounds = require("__base__.prototypes.entity.sounds")

return {
  type = "electric-energy-interface",
  icon = "__biological-machines-k2-assets__/graphics/intergalactic-transceiver/intergalactic-transceiver-icon.png",
  flags = {"player-creation", "not-rotatable"},
  map_color = { r = 0.37, g = 0.18, b = 0.47 },
  --placeable_by = { item = "kr-intergalactic-transceiver", count = 1 },
  collision_box = {{ -5.75, -5.25 }, { 5.75, 5.25 }},
  selection_box = {{ -6, -5.5 }, { 6, 5.5 }},
  drawing_box_vertical_extension = 1.25,
  max_health = 10000,
  dying_explosion = "nuclear-reactor-explosion",
  damaged_trigger_effect = hit_effects.entity(),
  resistances = {
    {type = "physical", percent = 75},
    {type = "fire", percent = 75},
    {type = "impact", percent = 75},
  },
  energy_source = {
    type = "electric",
    buffer_capacity = "50GJ",
    usage_priority = "primary-output",
    render_no_power_icon = false,
  },
  energy_production = "50GW",
  energy_usage = "0kW",
  working_sound = {
    sound = {
      variations = {
        {
          filename = "__biological-machines-k2-assets__/sounds/intergalactic-transceiver/intergalactic-transceiver-charge.ogg",
          volume = 1,
        },
        {
          filename = "__biological-machines-k2-assets__/sounds/intergalactic-transceiver/intergalactic-transceiver-charge.ogg",
          volume = 1,
        },
        {
          filename = "__biological-machines-k2-assets__/sounds/intergalactic-transceiver/intergalactic-transceiver-charge-morse.ogg",
          volume = 1,
        },
      },
    },
    idle_sound = {
      filename = "__biological-machines-k2-assets__/sounds/intergalactic-transceiver/intergalactic-transceiver.ogg",
      volume = 1,
    },
    max_sounds_per_prototype = 3,
    fade_in_ticks = 10,
    fade_out_ticks = 30,
  },
  continuous_animation = true,
  light = {
    intensity = 1.75,
    size = 30,
    shift = { 0, -0.5 },
    color = { r = 1, g = 0.2, b = 1 },
  },
  animation = {
    layers = {
      {
        filename = "__biological-machines-k2-assets__/graphics/intergalactic-transceiver/intergalactic-transceiver.png",
        width = 800,
        height = 800,
        scale = 0.5,
        frame_count = 1,
        repeat_count = 60,
        animation_speed = 0.3447,
        shift = { 0, -0.8 },
      },
      {
        filename = "__biological-machines-k2-assets__/graphics/intergalactic-transceiver/intergalactic-transceiver-sh.png",
        priority = "low",
        width = 867,
        height = 626,
        scale = 0.5,
        frame_count = 1,
        repeat_count = 60,
        draw_as_shadow = true,
        animation_speed = 0.3447,
        shift = { 0.52, 0.5 },
      },
      {
        filename = "__biological-machines-k2-assets__/graphics/intergalactic-transceiver/intergalactic-transceiver-charging.png",
        priority = "high",
        width = 800,
        height = 800,
        scale = 0.5,
        frame_count = 60,
        line_length = 10,
        animation_speed = 0.3447,
        shift = { 0, -0.8 },
        draw_as_glow = true,
      },
      {
        filename = "__biological-machines-k2-assets__/graphics/intergalactic-transceiver/intergalactic-transceiver-light.png",
        priority = "high",
        width = 800,
        height = 800,
        scale = 0.5,
        frame_count = 1,
        repeat_count = 60,
        animation_speed = 0.3447,
        shift = { 0, -0.8 },
        draw_as_light = true,
      },
      {
        filename = "__biological-machines-k2-assets__/graphics/intergalactic-transceiver/intergalactic-transceiver-charging-light.png",
        priority = "high",
        width = 800,
        height = 800,
        scale = 0.5,
        frame_count = 60,
        line_length = 10,
        animation_speed = 0.3447,
        shift = { 0, -0.8 },
        draw_as_light = true,
      },
    },
  },
}
